"""
Table 1: what the sample is.

Every later figure conditions on this table, so it is built first and everything
else reads the same two files it does — outputs/eval_table.csv for the pool and
the decisions, outputs/citations.csv for the outcome.

The column that earns the table its place is citation coverage BY DECISION. The
benchmark's claim is "this regime selects better from a pool of accepts and
rejects", so a measurement that finds accepted papers more reliably than rejected
ones rewards a regime for reaching into the accept pile regardless of quality.
OpenAlex ran a 26.3 pp differential, which is disqualifying for that claim; the S2
tier A+B table runs 3.9 pp. The residual is real and is reported here rather than
rounded away.

Unmatched papers are counted, never imputed as zero — a paper we could not find is
not a paper with no citations.

Run: python src/figures/table1_sample.py
"""
import os
import sys

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from figures import spec, figstyle as fs  # noqa: E402

OUT_CSV = "outputs/figures/table1_sample.csv"
TITLE = "Sample and citation coverage by year and decision"
OUT_TEX = "outputs/figures/table1_sample.tex"
OUT_PDF = "outputs/figures/table1_sample.pdf"
OUT_PNG = "outputs/figures/table1_sample.png"

YEARS = list(spec.YEARS)


def load():
    et = spec.read_eval_table()
    et["cited"] = et[spec.OUTCOME].notna()
    return et


def rows(et):
    out = []
    for yr in YEARS + ["all"]:
        d = et if yr == "all" else et[et.year == yr]
        acc, rej = d[d.accepted], d[~d.accepted]
        cov_a, cov_r = acc.cited.mean(), rej.cited.mean()
        tier = d.citation_tier.value_counts()
        out.append({
            "year": yr,
            "submissions": len(d),
            "accepts": int(d.accepted.sum()),
            "accept_rate": d.accepted.mean(),
            # n for every regime is the actual accept count, pinned per year
            "n_selected": int(d.accepted.sum()) if yr != "all" else np.nan,
            "median_cites_accepted": acc[spec.OUTCOME].median(),
            "median_cites_rejected": rej[spec.OUTCOME].median(),
            "cite_coverage": d.cited.mean(),
            "coverage_accepted": cov_a,
            "coverage_rejected": cov_r,
            # the number this table exists to expose
            "coverage_differential_pp": abs(cov_a - cov_r) * 100,
            "tier_a": int(tier.get("A", 0)),
            "tier_b": int(tier.get("B", 0)),
            "unmatched": int((~d.cited).sum()),
            "human_rating_coverage": d.mean_rating.notna().mean(),
        })
    return pd.DataFrame(out)


def to_tex(t):
    # `%` starts a comment in LaTeX, so a bare "36.0%" silently swallows the rest
    # of the row — including the \\ that ends it — and the table renders with
    # columns missing and no error. Every percent is escaped.
    def pct(v):
        return f"{v:.1%}".replace("%", "\\%")

    def f(r):
        yr = "All" if r.year == "all" else int(r.year)
        return (f"{yr} & {r.submissions:,} & {r.accepts:,} & {pct(r.accept_rate)} & "
                f"{r.median_cites_accepted:.0f} & {r.median_cites_rejected:.0f} & "
                f"{pct(r.coverage_accepted)} & {pct(r.coverage_rejected)} & "
                f"{r.coverage_differential_pp:.1f} \\\\")
    body = "\n".join(f(r) for r in t.itertuples())
    return (
        "% generated by src/figures/table1_sample.py — do not hand-edit\n"
        "\\begin{tabular}{lrrrrrrrr}\n\\toprule\n"
        "Year & Subs. & Acc. & Rate & \\multicolumn{2}{c}{Median cites} & "
        "\\multicolumn{2}{c}{Coverage} & Diff. \\\\\n"
        "& & & & Acc. & Rej. & Acc. & Rej. & (pp) \\\\\n\\midrule\n"
        f"{body}\n\\bottomrule\n\\end{{tabular}}\n"
    )


def render(t):
    """The same numbers as the .tex, drawn so they can be read without LaTeX."""
    def r(x):
        yr = "All" if x.year == "all" else str(int(x.year))
        return [yr, f"{x.submissions:,}", f"{x.accepts:,}", f"{x.accept_rate:.1%}",
                f"{x.median_cites_accepted:.0f}", f"{x.median_cites_rejected:.0f}",
                f"{x.coverage_accepted:.1%}", f"{x.coverage_rejected:.1%}",
                f"{x.coverage_differential_pp:.1f}"]

    body = [r(x) for x in t.itertuples()]
    fs.apply()
    fig = fs.table(
        header=[[("Year", 0, 0), ("Subs.", 1, 1), ("Acc.", 2, 2), ("Rate", 3, 3),
                 ("Median cites", 4, 5), ("Coverage", 6, 7), ("Diff.", 8, 8)],
                ["", "", "", "", "Acc.", "Rej.", "Acc.", "Rej.", "(pp)"]],
        body=body,
        align="lrrrrrrrr",
        colw=[0.8, 1.0, 0.9, 0.9, 0.95, 0.95, 1.0, 1.0, 0.85],
        rules=(len(body) - 1,),        # rule above the pooled row
        note="Outcome: Semantic Scholar citations by title + author matching.")
    fs.add_title(fig, TITLE)
    fig.savefig(OUT_PDF)
    fig.savefig(OUT_PNG, dpi=220)
    plt.close(fig)


def build():
    os.makedirs("outputs/figures", exist_ok=True)
    et = load()
    t = rows(et)
    t.to_csv(OUT_CSV, index=False)
    open(OUT_TEX, "w").write(to_tex(t))
    render(t)

    show = t[["year", "submissions", "accepts", "accept_rate",
              "median_cites_accepted", "median_cites_rejected",
              "coverage_accepted", "coverage_rejected",
              "coverage_differential_pp", "tier_a", "tier_b", "unmatched"]]
    with pd.option_context("display.width", 200, "display.max_columns", 50):
        print(show.to_string(index=False,
              formatters={"accept_rate": "{:.1%}".format,
                          "coverage_accepted": "{:.1%}".format,
                          "coverage_rejected": "{:.1%}".format,
                          "coverage_differential_pp": "{:.1f}".format}))
    print(f"\n-> {OUT_CSV}\n-> {OUT_TEX}\n-> {OUT_PDF}\n-> {OUT_PNG}")
    return t


def demo():
    t = build()
    a = t[t.year == "all"].iloc[0]
    assert a.submissions == 4567, a.submissions
    assert a.accepts == 1526, a.accepts
    # the differential is the headline; if it drifts past OpenAlex territory,
    # something upstream regressed and the table should not render quietly
    assert a.coverage_differential_pp < 10, a.coverage_differential_pp
    assert a.tier_a + a.tier_b + a.unmatched == a.submissions
    assert (t.median_cites_accepted > t.median_cites_rejected).all()
    print("ok — sample pinned, coverage differential "
          f"{a.coverage_differential_pp:.1f} pp")


if __name__ == "__main__":
    demo()
