"""
Export every distinct prompt used in the leakage/recall probes as a readable document.

Derived from outputs/leakage_ledger.csv, not hand-transcribed, so the document cannot drift
from what was actually sent. Each entry shows the verbatim prompt for a real call, the
sha1 of that string (so a reader can grep the ledger for it), and the call count.

Parameters (max_tokens, temperature) are only recorded for runs made after prompt logging
was added; earlier runs show UNVERIFIED rather than a guess.

Output: outputs/prompts_used.md
Run:    python src/audit/export_prompts.py
"""
import os
import json
import glob
import hashlib

import pandas as pd

LEDGER = "outputs/leakage_ledger.csv"
OUT = "outputs/prompts_used.md"

# What each run family's parameters were, where they can be established from the code or
# from logged trace fields. Anything not established is left UNVERIFIED on purpose.
PARAMS = {
    "oos_probes": {"temperature": "0", "logprobs": "top-5",
                   "max_tokens": "220 (Llama-3.3) / 2200 (Gemma-4, thinking model)",
                   "source": "src/probes/run_oos_probes.py"},
    "leakage_lap_v1": {"temperature": "UNVERIFIED", "logprobs": "top-20 requested",
                       "max_tokens": "2000 (MAX_TOKENS, src/probes/leakage_lap_v1.py)",
                       "source": "src/probes/leakage_lap_v1.py"},
    "leakage_fame_v1": {"temperature": "UNVERIFIED", "logprobs": "top-20 requested",
                        "max_tokens": "inherited from leakage_lap_v1.probe_one",
                        "source": "src/probes/leakage_fame_v1.py"},
    "leakage_controls": {"temperature": "UNVERIFIED", "logprobs": "top-20 requested",
                         "max_tokens": "inherited from leakage_lap_v1.probe_one",
                         "source": "src/probes/leakage_controls.py"},
}

PROBE_PURPOSE = {
    "lap": "outcome recall — does the model recall the accept/reject decision?",
    "fame": "impact recall — does the model recall the paper becoming widely cited?",
    "placebo": "false-positive floor — same question on a paper never submitted to ICLR",
    "wrongyear": "acquiescence check — same question with the venue year shifted by ±2",
    "fabricated": "false-positive floor (July run) — fabricated title",
    "wrong_year": "acquiescence check (July run)",
}


def main():
    if not os.path.exists(LEDGER):
        raise SystemExit(f"{LEDGER} missing — run src/build/build_leakage_ledger.py first")
    d = pd.read_csv(LEDGER)
    have = d[d["prompt_text"].notna() & d["prompt_text"].astype(str).str.len().gt(0)]

    L = ["# Prompts used in the leakage / recall probes", "",
         "Generated by `python src/audit/export_prompts.py` from `outputs/leakage_ledger.csv`. "
         "Every prompt below is the verbatim string sent for a real call, not a "
         "reconstruction written by hand. `prompt_sha1` identifies the exact string — "
         "grep it in the ledger to find every call that used it.", "",
         f"Ledger covers **{len(d):,} calls**; **{len(have):,}** have their prompt "
         f"recoverable. Missing: "
         f"{', '.join(sorted(set(d.loc[~d.index.isin(have.index), 'run_family']))) or 'none'}.",
         "", "## Provenance caveat", "",
         "Prompt strings for the July 2026 runs are **reconstructed** — rebuilt by calling "
         "each script's prompt function now, which is only faithful if that function has not "
         "changed since the run. Those runs did not log their prompts (and captured no "
         "reasoning traces: `outputs/leakage_lap_traces.jsonl` is 0 bytes). Runs from "
         "2026-08-03 onward log the prompt string and its hash at call time. The "
         "`prompt_provenance` column in the ledger states which applies per row.", ""]

    prov = d["prompt_provenance"].value_counts().to_dict()
    L += [f"- provenance breakdown: {prov}", ""]

    for family, g in have.groupby("run_family"):
        p = PARAMS.get(family, {})
        L += [f"## {family}", "",
              f"- source: `{p.get('source', 'UNVERIFIED')}`",
              f"- models: {', '.join(sorted(g['model'].dropna().unique()))}",
              f"- endpoint: {', '.join(sorted(g['endpoint'].dropna().unique()))}",
              f"- temperature: {p.get('temperature', 'UNVERIFIED')}",
              f"- max_tokens: {p.get('max_tokens', 'UNVERIFIED')}",
              f"- logprobs: {p.get('logprobs', 'UNVERIFIED')}",
              f"- run dates: {', '.join(sorted(g['run_date'].dropna().unique()))}",
              f"- calls: {len(g):,}", ""]
        for probe, gg in g.groupby("probe"):
            ex = gg.iloc[0]
            n_distinct = gg["prompt_sha1"].nunique()
            L += [f"### `{probe}` — {PROBE_PURPOSE.get(probe, 'UNVERIFIED purpose')}", "",
                  f"{len(gg):,} calls, {n_distinct:,} distinct prompt strings "
                  f"(one per paper, since the title and year are interpolated).", "",
                  f"Example — paper `{ex['paper_id']}`, arm `{ex['arm']}`, "
                  f"year sent `{ex['probe_year']}`, `prompt_sha1={ex['prompt_sha1']}`:", "",
                  "```text", str(ex["prompt_text"]).rstrip(), "```", ""]
            if str(ex.get("completion") or "").strip():
                L += ["Model's reply to that exact prompt:", "",
                      "```text", str(ex["completion"]).strip(), "```", ""]
            else:
                L += ["_No reply stored for this run — traces were not captured._", ""]

    L += ["## How to pull any prompt yourself", "",
          "```python", "import pandas as pd",
          'd = pd.read_csv("outputs/leakage_ledger.csv")',
          '# every distinct prompt template, one example each',
          'd.groupby(["run_family","probe"]).first()[["model","prompt_text"]]',
          '# the exact string sent for one paper',
          'd.query("paper_id == \'B1eWGREFvB\' and probe == \'lap\'").prompt_text.iloc[0]',
          "```", ""]

    open(OUT, "w").write("\n".join(L))

    # selfcheck: every (family, probe) with prompts must appear, and each example's
    # hash must match the ledger row it came from
    text = open(OUT).read()
    bad = []
    for (family, probe), gg in have.groupby(["run_family", "probe"]):
        if f"### `{probe}`" not in text or f"## {family}" not in text:
            bad.append(f"{family}/{probe} missing from document")
        ex = gg.iloc[0]
        if sha1(str(ex["prompt_text"])) != ex["prompt_sha1"]:
            bad.append(f"{family}/{probe} example hash does not match ledger "
                       f"({sha1(str(ex['prompt_text']))} vs {ex['prompt_sha1']})")
    print(f"Wrote {OUT} ({len(text):,} chars)")
    print("=== selfcheck ===")
    for b in bad:
        print(f"  FAIL {b}")
    if not bad:
        print("  every run_family/probe present; every example hash matches the ledger")


def sha1(s):
    return hashlib.sha1(str(s).encode()).hexdigest()[:12]


if __name__ == "__main__":
    main()
